// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/proto/v1/action.proto

package apiv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FieldType int32

const (
	FieldType_FIELD_TYPE_UNSPECIFIED FieldType = 0
	FieldType_FIELD_TYPE_STRING      FieldType = 1
	FieldType_FIELD_TYPE_INTEGER     FieldType = 2
	FieldType_FIELD_TYPE_FLOAT       FieldType = 3
	FieldType_FIELD_TYPE_BOOLEAN     FieldType = 4
	FieldType_FIELD_TYPE_ENUM        FieldType = 5
	FieldType_FIELD_TYPE_OBJECT      FieldType = 6
	FieldType_FIELD_TYPE_ARRAY       FieldType = 7
)

// Enum value maps for FieldType.
var (
	FieldType_name = map[int32]string{
		0: "FIELD_TYPE_UNSPECIFIED",
		1: "FIELD_TYPE_STRING",
		2: "FIELD_TYPE_INTEGER",
		3: "FIELD_TYPE_FLOAT",
		4: "FIELD_TYPE_BOOLEAN",
		5: "FIELD_TYPE_ENUM",
		6: "FIELD_TYPE_OBJECT",
		7: "FIELD_TYPE_ARRAY",
	}
	FieldType_value = map[string]int32{
		"FIELD_TYPE_UNSPECIFIED": 0,
		"FIELD_TYPE_STRING":      1,
		"FIELD_TYPE_INTEGER":     2,
		"FIELD_TYPE_FLOAT":       3,
		"FIELD_TYPE_BOOLEAN":     4,
		"FIELD_TYPE_ENUM":        5,
		"FIELD_TYPE_OBJECT":      6,
		"FIELD_TYPE_ARRAY":       7,
	}
)

func (x FieldType) Enum() *FieldType {
	p := new(FieldType)
	*p = x
	return p
}

func (x FieldType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FieldType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_v1_action_proto_enumTypes[0].Descriptor()
}

func (FieldType) Type() protoreflect.EnumType {
	return &file_api_proto_v1_action_proto_enumTypes[0]
}

func (x FieldType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FieldType.Descriptor instead.
func (FieldType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_v1_action_proto_rawDescGZIP(), []int{0}
}

type ActionStatus int32

const (
	ActionStatus_ACTION_STATUS_UNSPECIFIED      ActionStatus = 0
	ActionStatus_ACTION_STATUS_PENDING_APPROVAL ActionStatus = 1
	ActionStatus_ACTION_STATUS_PENDING          ActionStatus = 2
	ActionStatus_ACTION_STATUS_IN_PROGRESS      ActionStatus = 3
	ActionStatus_ACTION_STATUS_COMPLETED        ActionStatus = 4
	ActionStatus_ACTION_STATUS_FAILED           ActionStatus = 5
	ActionStatus_ACTION_STATUS_REJECTED         ActionStatus = 6
)

// Enum value maps for ActionStatus.
var (
	ActionStatus_name = map[int32]string{
		0: "ACTION_STATUS_UNSPECIFIED",
		1: "ACTION_STATUS_PENDING_APPROVAL",
		2: "ACTION_STATUS_PENDING",
		3: "ACTION_STATUS_IN_PROGRESS",
		4: "ACTION_STATUS_COMPLETED",
		5: "ACTION_STATUS_FAILED",
		6: "ACTION_STATUS_REJECTED",
	}
	ActionStatus_value = map[string]int32{
		"ACTION_STATUS_UNSPECIFIED":      0,
		"ACTION_STATUS_PENDING_APPROVAL": 1,
		"ACTION_STATUS_PENDING":          2,
		"ACTION_STATUS_IN_PROGRESS":      3,
		"ACTION_STATUS_COMPLETED":        4,
		"ACTION_STATUS_FAILED":           5,
		"ACTION_STATUS_REJECTED":         6,
	}
)

func (x ActionStatus) Enum() *ActionStatus {
	p := new(ActionStatus)
	*p = x
	return p
}

func (x ActionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_v1_action_proto_enumTypes[1].Descriptor()
}

func (ActionStatus) Type() protoreflect.EnumType {
	return &file_api_proto_v1_action_proto_enumTypes[1]
}

func (x ActionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActionStatus.Descriptor instead.
func (ActionStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_v1_action_proto_rawDescGZIP(), []int{1}
}

type ActionExecutionStatus int32

const (
	ActionExecutionStatus_ACTION_EXECUTION_STATUS_UNSPECIFIED ActionExecutionStatus = 0
	ActionExecutionStatus_ACTION_EXECUTION_STATUS_COMPLETED   ActionExecutionStatus = 1
	ActionExecutionStatus_ACTION_EXECUTION_STATUS_FAILED      ActionExecutionStatus = 2
)

// Enum value maps for ActionExecutionStatus.
var (
	ActionExecutionStatus_name = map[int32]string{
		0: "ACTION_EXECUTION_STATUS_UNSPECIFIED",
		1: "ACTION_EXECUTION_STATUS_COMPLETED",
		2: "ACTION_EXECUTION_STATUS_FAILED",
	}
	ActionExecutionStatus_value = map[string]int32{
		"ACTION_EXECUTION_STATUS_UNSPECIFIED": 0,
		"ACTION_EXECUTION_STATUS_COMPLETED":   1,
		"ACTION_EXECUTION_STATUS_FAILED":      2,
	}
)

func (x ActionExecutionStatus) Enum() *ActionExecutionStatus {
	p := new(ActionExecutionStatus)
	*p = x
	return p
}

func (x ActionExecutionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActionExecutionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_v1_action_proto_enumTypes[2].Descriptor()
}

func (ActionExecutionStatus) Type() protoreflect.EnumType {
	return &file_api_proto_v1_action_proto_enumTypes[2]
}

func (x ActionExecutionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActionExecutionStatus.Descriptor instead.
func (ActionExecutionStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_v1_action_proto_rawDescGZIP(), []int{2}
}

type ActionParameter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          FieldType              `protobuf:"varint,2,opt,name=type,proto3,enum=api.v1.FieldType" json:"type,omitempty"`
	Required      bool                   `protobuf:"varint,3,opt,name=required,proto3" json:"required,omitempty"`
	EnumValues    []string               `protobuf:"bytes,4,rep,name=enum_values,json=enumValues,proto3" json:"enum_values,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	DefaultValue  *structpb.Value        `protobuf:"bytes,6,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionParameter) Reset() {
	*x = ActionParameter{}
	mi := &file_api_proto_v1_action_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionParameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionParameter) ProtoMessage() {}

func (x *ActionParameter) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_action_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionParameter.ProtoReflect.Descriptor instead.
func (*ActionParameter) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_action_proto_rawDescGZIP(), []int{0}
}

func (x *ActionParameter) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ActionParameter) GetType() FieldType {
	if x != nil {
		return x.Type
	}
	return FieldType_FIELD_TYPE_UNSPECIFIED
}

func (x *ActionParameter) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *ActionParameter) GetEnumValues() []string {
	if x != nil {
		return x.EnumValues
	}
	return nil
}

func (x *ActionParameter) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ActionParameter) GetDefaultValue() *structpb.Value {
	if x != nil {
		return x.DefaultValue
	}
	return nil
}

type ActionResultField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          FieldType              `protobuf:"varint,2,opt,name=type,proto3,enum=api.v1.FieldType" json:"type,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Children      []*ActionResultField   `protobuf:"bytes,4,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionResultField) Reset() {
	*x = ActionResultField{}
	mi := &file_api_proto_v1_action_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionResultField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionResultField) ProtoMessage() {}

func (x *ActionResultField) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_action_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionResultField.ProtoReflect.Descriptor instead.
func (*ActionResultField) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_action_proto_rawDescGZIP(), []int{1}
}

func (x *ActionResultField) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ActionResultField) GetType() FieldType {
	if x != nil {
		return x.Type
	}
	return FieldType_FIELD_TYPE_UNSPECIFIED
}

func (x *ActionResultField) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ActionResultField) GetChildren() []*ActionResultField {
	if x != nil {
		return x.Children
	}
	return nil
}

type ActionSchema struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ActionType      string                 `protobuf:"bytes,2,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`
	DisplayName     string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description     string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Parameters      []*ActionParameter     `protobuf:"bytes,5,rep,name=parameters,proto3" json:"parameters,omitempty"`
	ResultSchema    []*ActionResultField   `protobuf:"bytes,6,rep,name=result_schema,json=resultSchema,proto3" json:"result_schema,omitempty"`
	RequireApproval bool                   `protobuf:"varint,7,opt,name=require_approval,json=requireApproval,proto3" json:"require_approval,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt       *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ActionSchema) Reset() {
	*x = ActionSchema{}
	mi := &file_api_proto_v1_action_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionSchema) ProtoMessage() {}

func (x *ActionSchema) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_action_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionSchema.ProtoReflect.Descriptor instead.
func (*ActionSchema) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_action_proto_rawDescGZIP(), []int{2}
}

func (x *ActionSchema) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ActionSchema) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

func (x *ActionSchema) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ActionSchema) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ActionSchema) GetParameters() []*ActionParameter {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *ActionSchema) GetResultSchema() []*ActionResultField {
	if x != nil {
		return x.ResultSchema
	}
	return nil
}

func (x *ActionSchema) GetRequireApproval() bool {
	if x != nil {
		return x.RequireApproval
	}
	return false
}

func (x *ActionSchema) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ActionSchema) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *ActionSchema) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type ActionExecution struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Id            string                     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TicketId      string                     `protobuf:"bytes,2,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	ActionType    string                     `protobuf:"bytes,3,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`
	Status        ActionStatus               `protobuf:"varint,4,opt,name=status,proto3,enum=api.v1.ActionStatus" json:"status,omitempty"`
	Parameters    map[string]*structpb.Value `protobuf:"bytes,5,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Result        *ActionExecutionResult     `protobuf:"bytes,6,opt,name=result,proto3" json:"result,omitempty"`
	ExecutingUser string                     `protobuf:"bytes,7,opt,name=executing_user,json=executingUser,proto3" json:"executing_user,omitempty"`
	CreatedAt     *timestamppb.Timestamp     `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp     `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ExecuteAt     *timestamppb.Timestamp     `protobuf:"bytes,10,opt,name=execute_at,json=executeAt,proto3" json:"execute_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionExecution) Reset() {
	*x = ActionExecution{}
	mi := &file_api_proto_v1_action_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionExecution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionExecution) ProtoMessage() {}

func (x *ActionExecution) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_action_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionExecution.ProtoReflect.Descriptor instead.
func (*ActionExecution) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_action_proto_rawDescGZIP(), []int{3}
}

func (x *ActionExecution) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ActionExecution) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

func (x *ActionExecution) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

func (x *ActionExecution) GetStatus() ActionStatus {
	if x != nil {
		return x.Status
	}
	return ActionStatus_ACTION_STATUS_UNSPECIFIED
}

func (x *ActionExecution) GetParameters() map[string]*structpb.Value {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *ActionExecution) GetResult() *ActionExecutionResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ActionExecution) GetExecutingUser() string {
	if x != nil {
		return x.ExecutingUser
	}
	return ""
}

func (x *ActionExecution) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ActionExecution) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *ActionExecution) GetExecuteAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExecuteAt
	}
	return nil
}

type ActionExecutionResult struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	ExecutionId   string                     `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	Status        ActionExecutionStatus      `protobuf:"varint,2,opt,name=status,proto3,enum=api.v1.ActionExecutionStatus" json:"status,omitempty"`
	Error         string                     `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	Logs          string                     `protobuf:"bytes,4,opt,name=logs,proto3" json:"logs,omitempty"`
	CompletedAt   *timestamppb.Timestamp     `protobuf:"bytes,5,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	Results       map[string]*structpb.Value `protobuf:"bytes,6,rep,name=results,proto3" json:"results,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionExecutionResult) Reset() {
	*x = ActionExecutionResult{}
	mi := &file_api_proto_v1_action_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionExecutionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionExecutionResult) ProtoMessage() {}

func (x *ActionExecutionResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_action_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionExecutionResult.ProtoReflect.Descriptor instead.
func (*ActionExecutionResult) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_action_proto_rawDescGZIP(), []int{4}
}

func (x *ActionExecutionResult) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *ActionExecutionResult) GetStatus() ActionExecutionStatus {
	if x != nil {
		return x.Status
	}
	return ActionExecutionStatus_ACTION_EXECUTION_STATUS_UNSPECIFIED
}

func (x *ActionExecutionResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ActionExecutionResult) GetLogs() string {
	if x != nil {
		return x.Logs
	}
	return ""
}

func (x *ActionExecutionResult) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *ActionExecutionResult) GetResults() map[string]*structpb.Value {
	if x != nil {
		return x.Results
	}
	return nil
}

type ListActionSchemasRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Ids             []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	ActionTypes     []string               `protobuf:"bytes,2,rep,name=action_types,json=actionTypes,proto3" json:"action_types,omitempty"`
	DisplayName     string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	RequireApproval *bool                  `protobuf:"varint,4,opt,name=require_approval,json=requireApproval,proto3,oneof" json:"require_approval,omitempty"`
	TimeRange       *TimeRange             `protobuf:"bytes,5,opt,name=time_range,json=timeRange,proto3" json:"time_range,omitempty"`
	Pagination      *PageRequest           `protobuf:"bytes,6,opt,name=pagination,proto3" json:"pagination,omitempty"`
	IncludeDeleted  bool                   `protobuf:"varint,7,opt,name=include_deleted,json=includeDeleted,proto3" json:"include_deleted,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListActionSchemasRequest) Reset() {
	*x = ListActionSchemasRequest{}
	mi := &file_api_proto_v1_action_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActionSchemasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActionSchemasRequest) ProtoMessage() {}

func (x *ListActionSchemasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_action_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActionSchemasRequest.ProtoReflect.Descriptor instead.
func (*ListActionSchemasRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_action_proto_rawDescGZIP(), []int{5}
}

func (x *ListActionSchemasRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *ListActionSchemasRequest) GetActionTypes() []string {
	if x != nil {
		return x.ActionTypes
	}
	return nil
}

func (x *ListActionSchemasRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ListActionSchemasRequest) GetRequireApproval() bool {
	if x != nil && x.RequireApproval != nil {
		return *x.RequireApproval
	}
	return false
}

func (x *ListActionSchemasRequest) GetTimeRange() *TimeRange {
	if x != nil {
		return x.TimeRange
	}
	return nil
}

func (x *ListActionSchemasRequest) GetPagination() *PageRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListActionSchemasRequest) GetIncludeDeleted() bool {
	if x != nil {
		return x.IncludeDeleted
	}
	return false
}

type ListActionSchemasResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schemas       []*ActionSchema        `protobuf:"bytes,1,rep,name=schemas,proto3" json:"schemas,omitempty"`
	Pagination    *PageInfo              `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActionSchemasResponse) Reset() {
	*x = ListActionSchemasResponse{}
	mi := &file_api_proto_v1_action_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActionSchemasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActionSchemasResponse) ProtoMessage() {}

func (x *ListActionSchemasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_action_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActionSchemasResponse.ProtoReflect.Descriptor instead.
func (*ListActionSchemasResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_action_proto_rawDescGZIP(), []int{6}
}

func (x *ListActionSchemasResponse) GetSchemas() []*ActionSchema {
	if x != nil {
		return x.Schemas
	}
	return nil
}

func (x *ListActionSchemasResponse) GetPagination() *PageInfo {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ExecuteActionRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	TicketId      string                     `protobuf:"bytes,1,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	ActionType    string                     `protobuf:"bytes,2,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`
	Parameters    map[string]*structpb.Value `protobuf:"bytes,3,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteActionRequest) Reset() {
	*x = ExecuteActionRequest{}
	mi := &file_api_proto_v1_action_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteActionRequest) ProtoMessage() {}

func (x *ExecuteActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_action_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteActionRequest.ProtoReflect.Descriptor instead.
func (*ExecuteActionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_action_proto_rawDescGZIP(), []int{7}
}

func (x *ExecuteActionRequest) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

func (x *ExecuteActionRequest) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

func (x *ExecuteActionRequest) GetParameters() map[string]*structpb.Value {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type GetActionExecutionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActionExecutionRequest) Reset() {
	*x = GetActionExecutionRequest{}
	mi := &file_api_proto_v1_action_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActionExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActionExecutionRequest) ProtoMessage() {}

func (x *GetActionExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_action_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActionExecutionRequest.ProtoReflect.Descriptor instead.
func (*GetActionExecutionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_action_proto_rawDescGZIP(), []int{8}
}

func (x *GetActionExecutionRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

type ListActionExecutionsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Ids            []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	TicketIds      []string               `protobuf:"bytes,2,rep,name=ticket_ids,json=ticketIds,proto3" json:"ticket_ids,omitempty"`
	ActionTypes    []string               `protobuf:"bytes,3,rep,name=action_types,json=actionTypes,proto3" json:"action_types,omitempty"`
	Statuses       []ActionStatus         `protobuf:"varint,4,rep,packed,name=statuses,proto3,enum=api.v1.ActionStatus" json:"statuses,omitempty"`
	ExecutingUsers []string               `protobuf:"bytes,5,rep,name=executing_users,json=executingUsers,proto3" json:"executing_users,omitempty"`
	TimeRange      *TimeRange             `protobuf:"bytes,6,opt,name=time_range,json=timeRange,proto3" json:"time_range,omitempty"`
	Pagination     *PageRequest           `protobuf:"bytes,7,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListActionExecutionsRequest) Reset() {
	*x = ListActionExecutionsRequest{}
	mi := &file_api_proto_v1_action_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActionExecutionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActionExecutionsRequest) ProtoMessage() {}

func (x *ListActionExecutionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_action_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActionExecutionsRequest.ProtoReflect.Descriptor instead.
func (*ListActionExecutionsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_action_proto_rawDescGZIP(), []int{9}
}

func (x *ListActionExecutionsRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *ListActionExecutionsRequest) GetTicketIds() []string {
	if x != nil {
		return x.TicketIds
	}
	return nil
}

func (x *ListActionExecutionsRequest) GetActionTypes() []string {
	if x != nil {
		return x.ActionTypes
	}
	return nil
}

func (x *ListActionExecutionsRequest) GetStatuses() []ActionStatus {
	if x != nil {
		return x.Statuses
	}
	return nil
}

func (x *ListActionExecutionsRequest) GetExecutingUsers() []string {
	if x != nil {
		return x.ExecutingUsers
	}
	return nil
}

func (x *ListActionExecutionsRequest) GetTimeRange() *TimeRange {
	if x != nil {
		return x.TimeRange
	}
	return nil
}

func (x *ListActionExecutionsRequest) GetPagination() *PageRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListActionExecutionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Executions    []*ActionExecution     `protobuf:"bytes,1,rep,name=executions,proto3" json:"executions,omitempty"`
	Pagination    *PageInfo              `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActionExecutionsResponse) Reset() {
	*x = ListActionExecutionsResponse{}
	mi := &file_api_proto_v1_action_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActionExecutionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActionExecutionsResponse) ProtoMessage() {}

func (x *ListActionExecutionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_action_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActionExecutionsResponse.ProtoReflect.Descriptor instead.
func (*ListActionExecutionsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_action_proto_rawDescGZIP(), []int{10}
}

func (x *ListActionExecutionsResponse) GetExecutions() []*ActionExecution {
	if x != nil {
		return x.Executions
	}
	return nil
}

func (x *ListActionExecutionsResponse) GetPagination() *PageInfo {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type UpdateActionSchemaRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ActionType      string                 `protobuf:"bytes,1,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`
	DisplayName     *string                `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3,oneof" json:"display_name,omitempty"`
	Description     *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Parameters      []*ActionParameter     `protobuf:"bytes,4,rep,name=parameters,proto3" json:"parameters,omitempty"`
	ResultSchema    []*ActionResultField   `protobuf:"bytes,5,rep,name=result_schema,json=resultSchema,proto3" json:"result_schema,omitempty"`
	RequireApproval *bool                  `protobuf:"varint,6,opt,name=require_approval,json=requireApproval,proto3,oneof" json:"require_approval,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateActionSchemaRequest) Reset() {
	*x = UpdateActionSchemaRequest{}
	mi := &file_api_proto_v1_action_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateActionSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateActionSchemaRequest) ProtoMessage() {}

func (x *UpdateActionSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_action_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateActionSchemaRequest.ProtoReflect.Descriptor instead.
func (*UpdateActionSchemaRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_action_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateActionSchemaRequest) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

func (x *UpdateActionSchemaRequest) GetDisplayName() string {
	if x != nil && x.DisplayName != nil {
		return *x.DisplayName
	}
	return ""
}

func (x *UpdateActionSchemaRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateActionSchemaRequest) GetParameters() []*ActionParameter {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *UpdateActionSchemaRequest) GetResultSchema() []*ActionResultField {
	if x != nil {
		return x.ResultSchema
	}
	return nil
}

func (x *UpdateActionSchemaRequest) GetRequireApproval() bool {
	if x != nil && x.RequireApproval != nil {
		return *x.RequireApproval
	}
	return false
}

type UpdateActionSchemaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schema        *ActionSchema          `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateActionSchemaResponse) Reset() {
	*x = UpdateActionSchemaResponse{}
	mi := &file_api_proto_v1_action_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateActionSchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateActionSchemaResponse) ProtoMessage() {}

func (x *UpdateActionSchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_action_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateActionSchemaResponse.ProtoReflect.Descriptor instead.
func (*UpdateActionSchemaResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_action_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateActionSchemaResponse) GetSchema() *ActionSchema {
	if x != nil {
		return x.Schema
	}
	return nil
}

type CreateActionSchemaRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ActionType      string                 `protobuf:"bytes,1,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`
	DisplayName     string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description     string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Parameters      []*ActionParameter     `protobuf:"bytes,4,rep,name=parameters,proto3" json:"parameters,omitempty"`
	ResultSchema    []*ActionResultField   `protobuf:"bytes,5,rep,name=result_schema,json=resultSchema,proto3" json:"result_schema,omitempty"`
	RequireApproval bool                   `protobuf:"varint,6,opt,name=require_approval,json=requireApproval,proto3" json:"require_approval,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateActionSchemaRequest) Reset() {
	*x = CreateActionSchemaRequest{}
	mi := &file_api_proto_v1_action_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateActionSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateActionSchemaRequest) ProtoMessage() {}

func (x *CreateActionSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_action_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateActionSchemaRequest.ProtoReflect.Descriptor instead.
func (*CreateActionSchemaRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_action_proto_rawDescGZIP(), []int{13}
}

func (x *CreateActionSchemaRequest) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

func (x *CreateActionSchemaRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *CreateActionSchemaRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateActionSchemaRequest) GetParameters() []*ActionParameter {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *CreateActionSchemaRequest) GetResultSchema() []*ActionResultField {
	if x != nil {
		return x.ResultSchema
	}
	return nil
}

func (x *CreateActionSchemaRequest) GetRequireApproval() bool {
	if x != nil {
		return x.RequireApproval
	}
	return false
}

type CreateActionSchemaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schema        *ActionSchema          `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateActionSchemaResponse) Reset() {
	*x = CreateActionSchemaResponse{}
	mi := &file_api_proto_v1_action_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateActionSchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateActionSchemaResponse) ProtoMessage() {}

func (x *CreateActionSchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_action_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateActionSchemaResponse.ProtoReflect.Descriptor instead.
func (*CreateActionSchemaResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_action_proto_rawDescGZIP(), []int{14}
}

func (x *CreateActionSchemaResponse) GetSchema() *ActionSchema {
	if x != nil {
		return x.Schema
	}
	return nil
}

type DeleteActionSchemaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActionType    string                 `protobuf:"bytes,1,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteActionSchemaRequest) Reset() {
	*x = DeleteActionSchemaRequest{}
	mi := &file_api_proto_v1_action_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteActionSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteActionSchemaRequest) ProtoMessage() {}

func (x *DeleteActionSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_action_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteActionSchemaRequest.ProtoReflect.Descriptor instead.
func (*DeleteActionSchemaRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_action_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteActionSchemaRequest) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

type DeleteActionSchemaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteActionSchemaResponse) Reset() {
	*x = DeleteActionSchemaResponse{}
	mi := &file_api_proto_v1_action_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteActionSchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteActionSchemaResponse) ProtoMessage() {}

func (x *DeleteActionSchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_action_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteActionSchemaResponse.ProtoReflect.Descriptor instead.
func (*DeleteActionSchemaResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_action_proto_rawDescGZIP(), []int{16}
}

var File_api_proto_v1_action_proto protoreflect.FileDescriptor

const file_api_proto_v1_action_proto_rawDesc = "" +
	"\n" +
	"\x19api/proto/v1/action.proto\x12\x06api.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x19api/proto/v1/common.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1aapi/proto/v1/options.proto\"\xe8\x01\n" +
	"\x0fActionParameter\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\x04type\x18\x02 \x01(\x0e2\x11.api.v1.FieldTypeR\x04type\x12\x1a\n" +
	"\brequired\x18\x03 \x01(\bR\brequired\x12\x1f\n" +
	"\venum_values\x18\x04 \x03(\tR\n" +
	"enumValues\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12;\n" +
	"\rdefault_value\x18\x06 \x01(\v2\x16.google.protobuf.ValueR\fdefaultValue\"\xa7\x01\n" +
	"\x11ActionResultField\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\x04type\x18\x02 \x01(\x0e2\x11.api.v1.FieldTypeR\x04type\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x125\n" +
	"\bchildren\x18\x04 \x03(\v2\x19.api.v1.ActionResultFieldR\bchildren\"\xd9\x03\n" +
	"\fActionSchema\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vaction_type\x18\x02 \x01(\tR\n" +
	"actionType\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x127\n" +
	"\n" +
	"parameters\x18\x05 \x03(\v2\x17.api.v1.ActionParameterR\n" +
	"parameters\x12>\n" +
	"\rresult_schema\x18\x06 \x03(\v2\x19.api.v1.ActionResultFieldR\fresultSchema\x12)\n" +
	"\x10require_approval\x18\a \x01(\bR\x0frequireApproval\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\"\xbc\x04\n" +
	"\x0fActionExecution\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tticket_id\x18\x02 \x01(\tR\bticketId\x12\x1f\n" +
	"\vaction_type\x18\x03 \x01(\tR\n" +
	"actionType\x12,\n" +
	"\x06status\x18\x04 \x01(\x0e2\x14.api.v1.ActionStatusR\x06status\x12G\n" +
	"\n" +
	"parameters\x18\x05 \x03(\v2'.api.v1.ActionExecution.ParametersEntryR\n" +
	"parameters\x125\n" +
	"\x06result\x18\x06 \x01(\v2\x1d.api.v1.ActionExecutionResultR\x06result\x12%\n" +
	"\x0eexecuting_user\x18\a \x01(\tR\rexecutingUser\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"execute_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\texecuteAt\x1aU\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01\"\xf4\x02\n" +
	"\x15ActionExecutionResult\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x125\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1d.api.v1.ActionExecutionStatusR\x06status\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\x12\n" +
	"\x04logs\x18\x04 \x01(\tR\x04logs\x12=\n" +
	"\fcompleted_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x12D\n" +
	"\aresults\x18\x06 \x03(\v2*.api.v1.ActionExecutionResult.ResultsEntryR\aresults\x1aR\n" +
	"\fResultsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01\"\xc7\x02\n" +
	"\x18ListActionSchemasRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\x12!\n" +
	"\faction_types\x18\x02 \x03(\tR\vactionTypes\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12.\n" +
	"\x10require_approval\x18\x04 \x01(\bH\x00R\x0frequireApproval\x88\x01\x01\x120\n" +
	"\n" +
	"time_range\x18\x05 \x01(\v2\x11.api.v1.TimeRangeR\ttimeRange\x123\n" +
	"\n" +
	"pagination\x18\x06 \x01(\v2\x13.api.v1.PageRequestR\n" +
	"pagination\x12'\n" +
	"\x0finclude_deleted\x18\a \x01(\bR\x0eincludeDeletedB\x13\n" +
	"\x11_require_approval\"}\n" +
	"\x19ListActionSchemasResponse\x12.\n" +
	"\aschemas\x18\x01 \x03(\v2\x14.api.v1.ActionSchemaR\aschemas\x120\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x10.api.v1.PageInfoR\n" +
	"pagination\"\xf9\x01\n" +
	"\x14ExecuteActionRequest\x12\x1b\n" +
	"\tticket_id\x18\x01 \x01(\tR\bticketId\x12\x1f\n" +
	"\vaction_type\x18\x02 \x01(\tR\n" +
	"actionType\x12L\n" +
	"\n" +
	"parameters\x18\x03 \x03(\v2,.api.v1.ExecuteActionRequest.ParametersEntryR\n" +
	"parameters\x1aU\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01\">\n" +
	"\x19GetActionExecutionRequest\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\"\xb3\x02\n" +
	"\x1bListActionExecutionsRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\x12\x1d\n" +
	"\n" +
	"ticket_ids\x18\x02 \x03(\tR\tticketIds\x12!\n" +
	"\faction_types\x18\x03 \x03(\tR\vactionTypes\x120\n" +
	"\bstatuses\x18\x04 \x03(\x0e2\x14.api.v1.ActionStatusR\bstatuses\x12'\n" +
	"\x0fexecuting_users\x18\x05 \x03(\tR\x0eexecutingUsers\x120\n" +
	"\n" +
	"time_range\x18\x06 \x01(\v2\x11.api.v1.TimeRangeR\ttimeRange\x123\n" +
	"\n" +
	"pagination\x18\a \x01(\v2\x13.api.v1.PageRequestR\n" +
	"pagination\"\x89\x01\n" +
	"\x1cListActionExecutionsResponse\x127\n" +
	"\n" +
	"executions\x18\x01 \x03(\v2\x17.api.v1.ActionExecutionR\n" +
	"executions\x120\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x10.api.v1.PageInfoR\n" +
	"pagination\"\xea\x02\n" +
	"\x19UpdateActionSchemaRequest\x12\x1f\n" +
	"\vaction_type\x18\x01 \x01(\tR\n" +
	"actionType\x12&\n" +
	"\fdisplay_name\x18\x02 \x01(\tH\x00R\vdisplayName\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01\x127\n" +
	"\n" +
	"parameters\x18\x04 \x03(\v2\x17.api.v1.ActionParameterR\n" +
	"parameters\x12>\n" +
	"\rresult_schema\x18\x05 \x03(\v2\x19.api.v1.ActionResultFieldR\fresultSchema\x12.\n" +
	"\x10require_approval\x18\x06 \x01(\bH\x02R\x0frequireApproval\x88\x01\x01B\x0f\n" +
	"\r_display_nameB\x0e\n" +
	"\f_descriptionB\x13\n" +
	"\x11_require_approval\"J\n" +
	"\x1aUpdateActionSchemaResponse\x12,\n" +
	"\x06schema\x18\x01 \x01(\v2\x14.api.v1.ActionSchemaR\x06schema\"\xa5\x02\n" +
	"\x19CreateActionSchemaRequest\x12\x1f\n" +
	"\vaction_type\x18\x01 \x01(\tR\n" +
	"actionType\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x127\n" +
	"\n" +
	"parameters\x18\x04 \x03(\v2\x17.api.v1.ActionParameterR\n" +
	"parameters\x12>\n" +
	"\rresult_schema\x18\x05 \x03(\v2\x19.api.v1.ActionResultFieldR\fresultSchema\x12)\n" +
	"\x10require_approval\x18\x06 \x01(\bR\x0frequireApproval\"J\n" +
	"\x1aCreateActionSchemaResponse\x12,\n" +
	"\x06schema\x18\x01 \x01(\v2\x14.api.v1.ActionSchemaR\x06schema\"<\n" +
	"\x19DeleteActionSchemaRequest\x12\x1f\n" +
	"\vaction_type\x18\x01 \x01(\tR\n" +
	"actionType\"\x1c\n" +
	"\x1aDeleteActionSchemaResponse*\xc6\x01\n" +
	"\tFieldType\x12\x1a\n" +
	"\x16FIELD_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11FIELD_TYPE_STRING\x10\x01\x12\x16\n" +
	"\x12FIELD_TYPE_INTEGER\x10\x02\x12\x14\n" +
	"\x10FIELD_TYPE_FLOAT\x10\x03\x12\x16\n" +
	"\x12FIELD_TYPE_BOOLEAN\x10\x04\x12\x13\n" +
	"\x0fFIELD_TYPE_ENUM\x10\x05\x12\x15\n" +
	"\x11FIELD_TYPE_OBJECT\x10\x06\x12\x14\n" +
	"\x10FIELD_TYPE_ARRAY\x10\a*\xde\x01\n" +
	"\fActionStatus\x12\x1d\n" +
	"\x19ACTION_STATUS_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eACTION_STATUS_PENDING_APPROVAL\x10\x01\x12\x19\n" +
	"\x15ACTION_STATUS_PENDING\x10\x02\x12\x1d\n" +
	"\x19ACTION_STATUS_IN_PROGRESS\x10\x03\x12\x1b\n" +
	"\x17ACTION_STATUS_COMPLETED\x10\x04\x12\x18\n" +
	"\x14ACTION_STATUS_FAILED\x10\x05\x12\x1a\n" +
	"\x16ACTION_STATUS_REJECTED\x10\x06*\x8b\x01\n" +
	"\x15ActionExecutionStatus\x12'\n" +
	"#ACTION_EXECUTION_STATUS_UNSPECIFIED\x10\x00\x12%\n" +
	"!ACTION_EXECUTION_STATUS_COMPLETED\x10\x01\x12\"\n" +
	"\x1eACTION_EXECUTION_STATUS_FAILED\x10\x022\xbc\b\n" +
	"\rActionService\x12\x83\x01\n" +
	"\rExecuteAction\x12\x1c.api.v1.ExecuteActionRequest\x1a\x17.api.v1.ActionExecution\";\x82\xb5\x18\x1d\n" +
	"\rwrite:actions\x12\x05admin\x12\x05agent\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/api/v1/actions\x12\x94\x01\n" +
	"\x12GetActionExecution\x12!.api.v1.GetActionExecutionRequest\x1a\x17.api.v1.ActionExecution\"B\x82\xb5\x18\x0e\n" +
	"\fread:actions\x82\xd3\xe4\x93\x02*\x12(/api/v1/action-executions/{execution_id}\x12\x96\x01\n" +
	"\x14ListActionExecutions\x12#.api.v1.ListActionExecutionsRequest\x1a$.api.v1.ListActionExecutionsResponse\"3\x82\xb5\x18\x0e\n" +
	"\fread:actions\x82\xd3\xe4\x93\x02\x1b\x12\x19/api/v1/action-executions\x12\x98\x01\n" +
	"\x12CreateActionSchema\x12!.api.v1.CreateActionSchemaRequest\x1a\".api.v1.CreateActionSchemaResponse\";\x82\xb5\x18\x16\n" +
	"\rwrite:actions\x12\x05admin\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/api/v1/action-schemas\x12\x8a\x01\n" +
	"\x11ListActionSchemas\x12 .api.v1.ListActionSchemasRequest\x1a!.api.v1.ListActionSchemasResponse\"0\x82\xb5\x18\x0e\n" +
	"\fread:actions\x82\xd3\xe4\x93\x02\x18\x12\x16/api/v1/action-schemas\x12\xa6\x01\n" +
	"\x12UpdateActionSchema\x12!.api.v1.UpdateActionSchemaRequest\x1a\".api.v1.UpdateActionSchemaResponse\"I\x82\xb5\x18\x16\n" +
	"\rwrite:actions\x12\x05admin\x82\xd3\xe4\x93\x02):\x01*\x1a$/api/v1/action-schemas/{action_type}\x12\xa3\x01\n" +
	"\x12DeleteActionSchema\x12!.api.v1.DeleteActionSchemaRequest\x1a\".api.v1.DeleteActionSchemaResponse\"F\x82\xb5\x18\x16\n" +
	"\rwrite:actions\x12\x05admin\x82\xd3\xe4\x93\x02&*$/api/v1/action-schemas/{action_type}B7Z5github.com/squall-chua/go-support-ticket/api/v1;apiv1b\x06proto3"

var (
	file_api_proto_v1_action_proto_rawDescOnce sync.Once
	file_api_proto_v1_action_proto_rawDescData []byte
)

func file_api_proto_v1_action_proto_rawDescGZIP() []byte {
	file_api_proto_v1_action_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_action_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_action_proto_rawDesc), len(file_api_proto_v1_action_proto_rawDesc)))
	})
	return file_api_proto_v1_action_proto_rawDescData
}

var file_api_proto_v1_action_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_api_proto_v1_action_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_api_proto_v1_action_proto_goTypes = []any{
	(FieldType)(0),                       // 0: api.v1.FieldType
	(ActionStatus)(0),                    // 1: api.v1.ActionStatus
	(ActionExecutionStatus)(0),           // 2: api.v1.ActionExecutionStatus
	(*ActionParameter)(nil),              // 3: api.v1.ActionParameter
	(*ActionResultField)(nil),            // 4: api.v1.ActionResultField
	(*ActionSchema)(nil),                 // 5: api.v1.ActionSchema
	(*ActionExecution)(nil),              // 6: api.v1.ActionExecution
	(*ActionExecutionResult)(nil),        // 7: api.v1.ActionExecutionResult
	(*ListActionSchemasRequest)(nil),     // 8: api.v1.ListActionSchemasRequest
	(*ListActionSchemasResponse)(nil),    // 9: api.v1.ListActionSchemasResponse
	(*ExecuteActionRequest)(nil),         // 10: api.v1.ExecuteActionRequest
	(*GetActionExecutionRequest)(nil),    // 11: api.v1.GetActionExecutionRequest
	(*ListActionExecutionsRequest)(nil),  // 12: api.v1.ListActionExecutionsRequest
	(*ListActionExecutionsResponse)(nil), // 13: api.v1.ListActionExecutionsResponse
	(*UpdateActionSchemaRequest)(nil),    // 14: api.v1.UpdateActionSchemaRequest
	(*UpdateActionSchemaResponse)(nil),   // 15: api.v1.UpdateActionSchemaResponse
	(*CreateActionSchemaRequest)(nil),    // 16: api.v1.CreateActionSchemaRequest
	(*CreateActionSchemaResponse)(nil),   // 17: api.v1.CreateActionSchemaResponse
	(*DeleteActionSchemaRequest)(nil),    // 18: api.v1.DeleteActionSchemaRequest
	(*DeleteActionSchemaResponse)(nil),   // 19: api.v1.DeleteActionSchemaResponse
	nil,                                  // 20: api.v1.ActionExecution.ParametersEntry
	nil,                                  // 21: api.v1.ActionExecutionResult.ResultsEntry
	nil,                                  // 22: api.v1.ExecuteActionRequest.ParametersEntry
	(*structpb.Value)(nil),               // 23: google.protobuf.Value
	(*timestamppb.Timestamp)(nil),        // 24: google.protobuf.Timestamp
	(*TimeRange)(nil),                    // 25: api.v1.TimeRange
	(*PageRequest)(nil),                  // 26: api.v1.PageRequest
	(*PageInfo)(nil),                     // 27: api.v1.PageInfo
}
var file_api_proto_v1_action_proto_depIdxs = []int32{
	0,  // 0: api.v1.ActionParameter.type:type_name -> api.v1.FieldType
	23, // 1: api.v1.ActionParameter.default_value:type_name -> google.protobuf.Value
	0,  // 2: api.v1.ActionResultField.type:type_name -> api.v1.FieldType
	4,  // 3: api.v1.ActionResultField.children:type_name -> api.v1.ActionResultField
	3,  // 4: api.v1.ActionSchema.parameters:type_name -> api.v1.ActionParameter
	4,  // 5: api.v1.ActionSchema.result_schema:type_name -> api.v1.ActionResultField
	24, // 6: api.v1.ActionSchema.created_at:type_name -> google.protobuf.Timestamp
	24, // 7: api.v1.ActionSchema.updated_at:type_name -> google.protobuf.Timestamp
	24, // 8: api.v1.ActionSchema.deleted_at:type_name -> google.protobuf.Timestamp
	1,  // 9: api.v1.ActionExecution.status:type_name -> api.v1.ActionStatus
	20, // 10: api.v1.ActionExecution.parameters:type_name -> api.v1.ActionExecution.ParametersEntry
	7,  // 11: api.v1.ActionExecution.result:type_name -> api.v1.ActionExecutionResult
	24, // 12: api.v1.ActionExecution.created_at:type_name -> google.protobuf.Timestamp
	24, // 13: api.v1.ActionExecution.updated_at:type_name -> google.protobuf.Timestamp
	24, // 14: api.v1.ActionExecution.execute_at:type_name -> google.protobuf.Timestamp
	2,  // 15: api.v1.ActionExecutionResult.status:type_name -> api.v1.ActionExecutionStatus
	24, // 16: api.v1.ActionExecutionResult.completed_at:type_name -> google.protobuf.Timestamp
	21, // 17: api.v1.ActionExecutionResult.results:type_name -> api.v1.ActionExecutionResult.ResultsEntry
	25, // 18: api.v1.ListActionSchemasRequest.time_range:type_name -> api.v1.TimeRange
	26, // 19: api.v1.ListActionSchemasRequest.pagination:type_name -> api.v1.PageRequest
	5,  // 20: api.v1.ListActionSchemasResponse.schemas:type_name -> api.v1.ActionSchema
	27, // 21: api.v1.ListActionSchemasResponse.pagination:type_name -> api.v1.PageInfo
	22, // 22: api.v1.ExecuteActionRequest.parameters:type_name -> api.v1.ExecuteActionRequest.ParametersEntry
	1,  // 23: api.v1.ListActionExecutionsRequest.statuses:type_name -> api.v1.ActionStatus
	25, // 24: api.v1.ListActionExecutionsRequest.time_range:type_name -> api.v1.TimeRange
	26, // 25: api.v1.ListActionExecutionsRequest.pagination:type_name -> api.v1.PageRequest
	6,  // 26: api.v1.ListActionExecutionsResponse.executions:type_name -> api.v1.ActionExecution
	27, // 27: api.v1.ListActionExecutionsResponse.pagination:type_name -> api.v1.PageInfo
	3,  // 28: api.v1.UpdateActionSchemaRequest.parameters:type_name -> api.v1.ActionParameter
	4,  // 29: api.v1.UpdateActionSchemaRequest.result_schema:type_name -> api.v1.ActionResultField
	5,  // 30: api.v1.UpdateActionSchemaResponse.schema:type_name -> api.v1.ActionSchema
	3,  // 31: api.v1.CreateActionSchemaRequest.parameters:type_name -> api.v1.ActionParameter
	4,  // 32: api.v1.CreateActionSchemaRequest.result_schema:type_name -> api.v1.ActionResultField
	5,  // 33: api.v1.CreateActionSchemaResponse.schema:type_name -> api.v1.ActionSchema
	23, // 34: api.v1.ActionExecution.ParametersEntry.value:type_name -> google.protobuf.Value
	23, // 35: api.v1.ActionExecutionResult.ResultsEntry.value:type_name -> google.protobuf.Value
	23, // 36: api.v1.ExecuteActionRequest.ParametersEntry.value:type_name -> google.protobuf.Value
	10, // 37: api.v1.ActionService.ExecuteAction:input_type -> api.v1.ExecuteActionRequest
	11, // 38: api.v1.ActionService.GetActionExecution:input_type -> api.v1.GetActionExecutionRequest
	12, // 39: api.v1.ActionService.ListActionExecutions:input_type -> api.v1.ListActionExecutionsRequest
	16, // 40: api.v1.ActionService.CreateActionSchema:input_type -> api.v1.CreateActionSchemaRequest
	8,  // 41: api.v1.ActionService.ListActionSchemas:input_type -> api.v1.ListActionSchemasRequest
	14, // 42: api.v1.ActionService.UpdateActionSchema:input_type -> api.v1.UpdateActionSchemaRequest
	18, // 43: api.v1.ActionService.DeleteActionSchema:input_type -> api.v1.DeleteActionSchemaRequest
	6,  // 44: api.v1.ActionService.ExecuteAction:output_type -> api.v1.ActionExecution
	6,  // 45: api.v1.ActionService.GetActionExecution:output_type -> api.v1.ActionExecution
	13, // 46: api.v1.ActionService.ListActionExecutions:output_type -> api.v1.ListActionExecutionsResponse
	17, // 47: api.v1.ActionService.CreateActionSchema:output_type -> api.v1.CreateActionSchemaResponse
	9,  // 48: api.v1.ActionService.ListActionSchemas:output_type -> api.v1.ListActionSchemasResponse
	15, // 49: api.v1.ActionService.UpdateActionSchema:output_type -> api.v1.UpdateActionSchemaResponse
	19, // 50: api.v1.ActionService.DeleteActionSchema:output_type -> api.v1.DeleteActionSchemaResponse
	44, // [44:51] is the sub-list for method output_type
	37, // [37:44] is the sub-list for method input_type
	37, // [37:37] is the sub-list for extension type_name
	37, // [37:37] is the sub-list for extension extendee
	0,  // [0:37] is the sub-list for field type_name
}

func init() { file_api_proto_v1_action_proto_init() }
func file_api_proto_v1_action_proto_init() {
	if File_api_proto_v1_action_proto != nil {
		return
	}
	file_api_proto_v1_common_proto_init()
	file_api_proto_v1_options_proto_init()
	file_api_proto_v1_action_proto_msgTypes[5].OneofWrappers = []any{}
	file_api_proto_v1_action_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_action_proto_rawDesc), len(file_api_proto_v1_action_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_action_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_action_proto_depIdxs,
		EnumInfos:         file_api_proto_v1_action_proto_enumTypes,
		MessageInfos:      file_api_proto_v1_action_proto_msgTypes,
	}.Build()
	File_api_proto_v1_action_proto = out.File
	file_api_proto_v1_action_proto_goTypes = nil
	file_api_proto_v1_action_proto_depIdxs = nil
}
