// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: api/proto/v1/action.proto

package apiv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ActionService_ExecuteAction_FullMethodName        = "/api.v1.ActionService/ExecuteAction"
	ActionService_CancelAction_FullMethodName         = "/api.v1.ActionService/CancelAction"
	ActionService_GetActionExecution_FullMethodName   = "/api.v1.ActionService/GetActionExecution"
	ActionService_ListActionExecutions_FullMethodName = "/api.v1.ActionService/ListActionExecutions"
	ActionService_CreateActionSchema_FullMethodName   = "/api.v1.ActionService/CreateActionSchema"
	ActionService_ListActionSchemas_FullMethodName    = "/api.v1.ActionService/ListActionSchemas"
	ActionService_UpdateActionSchema_FullMethodName   = "/api.v1.ActionService/UpdateActionSchema"
	ActionService_DeleteActionSchema_FullMethodName   = "/api.v1.ActionService/DeleteActionSchema"
)

// ActionServiceClient is the client API for ActionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ActionServiceClient interface {
	ExecuteAction(ctx context.Context, in *ExecuteActionRequest, opts ...grpc.CallOption) (*ActionExecution, error)
	CancelAction(ctx context.Context, in *CancelActionRequest, opts ...grpc.CallOption) (*CancelActionResponse, error)
	GetActionExecution(ctx context.Context, in *GetActionExecutionRequest, opts ...grpc.CallOption) (*ActionExecution, error)
	ListActionExecutions(ctx context.Context, in *ListActionExecutionsRequest, opts ...grpc.CallOption) (*ListActionExecutionsResponse, error)
	CreateActionSchema(ctx context.Context, in *CreateActionSchemaRequest, opts ...grpc.CallOption) (*CreateActionSchemaResponse, error)
	ListActionSchemas(ctx context.Context, in *ListActionSchemasRequest, opts ...grpc.CallOption) (*ListActionSchemasResponse, error)
	UpdateActionSchema(ctx context.Context, in *UpdateActionSchemaRequest, opts ...grpc.CallOption) (*UpdateActionSchemaResponse, error)
	DeleteActionSchema(ctx context.Context, in *DeleteActionSchemaRequest, opts ...grpc.CallOption) (*DeleteActionSchemaResponse, error)
}

type actionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewActionServiceClient(cc grpc.ClientConnInterface) ActionServiceClient {
	return &actionServiceClient{cc}
}

func (c *actionServiceClient) ExecuteAction(ctx context.Context, in *ExecuteActionRequest, opts ...grpc.CallOption) (*ActionExecution, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionExecution)
	err := c.cc.Invoke(ctx, ActionService_ExecuteAction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *actionServiceClient) CancelAction(ctx context.Context, in *CancelActionRequest, opts ...grpc.CallOption) (*CancelActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelActionResponse)
	err := c.cc.Invoke(ctx, ActionService_CancelAction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *actionServiceClient) GetActionExecution(ctx context.Context, in *GetActionExecutionRequest, opts ...grpc.CallOption) (*ActionExecution, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionExecution)
	err := c.cc.Invoke(ctx, ActionService_GetActionExecution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *actionServiceClient) ListActionExecutions(ctx context.Context, in *ListActionExecutionsRequest, opts ...grpc.CallOption) (*ListActionExecutionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListActionExecutionsResponse)
	err := c.cc.Invoke(ctx, ActionService_ListActionExecutions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *actionServiceClient) CreateActionSchema(ctx context.Context, in *CreateActionSchemaRequest, opts ...grpc.CallOption) (*CreateActionSchemaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateActionSchemaResponse)
	err := c.cc.Invoke(ctx, ActionService_CreateActionSchema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *actionServiceClient) ListActionSchemas(ctx context.Context, in *ListActionSchemasRequest, opts ...grpc.CallOption) (*ListActionSchemasResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListActionSchemasResponse)
	err := c.cc.Invoke(ctx, ActionService_ListActionSchemas_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *actionServiceClient) UpdateActionSchema(ctx context.Context, in *UpdateActionSchemaRequest, opts ...grpc.CallOption) (*UpdateActionSchemaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateActionSchemaResponse)
	err := c.cc.Invoke(ctx, ActionService_UpdateActionSchema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *actionServiceClient) DeleteActionSchema(ctx context.Context, in *DeleteActionSchemaRequest, opts ...grpc.CallOption) (*DeleteActionSchemaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteActionSchemaResponse)
	err := c.cc.Invoke(ctx, ActionService_DeleteActionSchema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ActionServiceServer is the server API for ActionService service.
// All implementations should embed UnimplementedActionServiceServer
// for forward compatibility.
type ActionServiceServer interface {
	ExecuteAction(context.Context, *ExecuteActionRequest) (*ActionExecution, error)
	CancelAction(context.Context, *CancelActionRequest) (*CancelActionResponse, error)
	GetActionExecution(context.Context, *GetActionExecutionRequest) (*ActionExecution, error)
	ListActionExecutions(context.Context, *ListActionExecutionsRequest) (*ListActionExecutionsResponse, error)
	CreateActionSchema(context.Context, *CreateActionSchemaRequest) (*CreateActionSchemaResponse, error)
	ListActionSchemas(context.Context, *ListActionSchemasRequest) (*ListActionSchemasResponse, error)
	UpdateActionSchema(context.Context, *UpdateActionSchemaRequest) (*UpdateActionSchemaResponse, error)
	DeleteActionSchema(context.Context, *DeleteActionSchemaRequest) (*DeleteActionSchemaResponse, error)
}

// UnimplementedActionServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedActionServiceServer struct{}

func (UnimplementedActionServiceServer) ExecuteAction(context.Context, *ExecuteActionRequest) (*ActionExecution, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteAction not implemented")
}
func (UnimplementedActionServiceServer) CancelAction(context.Context, *CancelActionRequest) (*CancelActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelAction not implemented")
}
func (UnimplementedActionServiceServer) GetActionExecution(context.Context, *GetActionExecutionRequest) (*ActionExecution, error) {
	return nil, status.Error(codes.Unimplemented, "method GetActionExecution not implemented")
}
func (UnimplementedActionServiceServer) ListActionExecutions(context.Context, *ListActionExecutionsRequest) (*ListActionExecutionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListActionExecutions not implemented")
}
func (UnimplementedActionServiceServer) CreateActionSchema(context.Context, *CreateActionSchemaRequest) (*CreateActionSchemaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateActionSchema not implemented")
}
func (UnimplementedActionServiceServer) ListActionSchemas(context.Context, *ListActionSchemasRequest) (*ListActionSchemasResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListActionSchemas not implemented")
}
func (UnimplementedActionServiceServer) UpdateActionSchema(context.Context, *UpdateActionSchemaRequest) (*UpdateActionSchemaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateActionSchema not implemented")
}
func (UnimplementedActionServiceServer) DeleteActionSchema(context.Context, *DeleteActionSchemaRequest) (*DeleteActionSchemaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteActionSchema not implemented")
}
func (UnimplementedActionServiceServer) testEmbeddedByValue() {}

// UnsafeActionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ActionServiceServer will
// result in compilation errors.
type UnsafeActionServiceServer interface {
	mustEmbedUnimplementedActionServiceServer()
}

func RegisterActionServiceServer(s grpc.ServiceRegistrar, srv ActionServiceServer) {
	// If the following call panics, it indicates UnimplementedActionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ActionService_ServiceDesc, srv)
}

func _ActionService_ExecuteAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActionServiceServer).ExecuteAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ActionService_ExecuteAction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActionServiceServer).ExecuteAction(ctx, req.(*ExecuteActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ActionService_CancelAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActionServiceServer).CancelAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ActionService_CancelAction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActionServiceServer).CancelAction(ctx, req.(*CancelActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ActionService_GetActionExecution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActionExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActionServiceServer).GetActionExecution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ActionService_GetActionExecution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActionServiceServer).GetActionExecution(ctx, req.(*GetActionExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ActionService_ListActionExecutions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListActionExecutionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActionServiceServer).ListActionExecutions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ActionService_ListActionExecutions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActionServiceServer).ListActionExecutions(ctx, req.(*ListActionExecutionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ActionService_CreateActionSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateActionSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActionServiceServer).CreateActionSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ActionService_CreateActionSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActionServiceServer).CreateActionSchema(ctx, req.(*CreateActionSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ActionService_ListActionSchemas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListActionSchemasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActionServiceServer).ListActionSchemas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ActionService_ListActionSchemas_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActionServiceServer).ListActionSchemas(ctx, req.(*ListActionSchemasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ActionService_UpdateActionSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateActionSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActionServiceServer).UpdateActionSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ActionService_UpdateActionSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActionServiceServer).UpdateActionSchema(ctx, req.(*UpdateActionSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ActionService_DeleteActionSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteActionSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActionServiceServer).DeleteActionSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ActionService_DeleteActionSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActionServiceServer).DeleteActionSchema(ctx, req.(*DeleteActionSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ActionService_ServiceDesc is the grpc.ServiceDesc for ActionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ActionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.v1.ActionService",
	HandlerType: (*ActionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteAction",
			Handler:    _ActionService_ExecuteAction_Handler,
		},
		{
			MethodName: "CancelAction",
			Handler:    _ActionService_CancelAction_Handler,
		},
		{
			MethodName: "GetActionExecution",
			Handler:    _ActionService_GetActionExecution_Handler,
		},
		{
			MethodName: "ListActionExecutions",
			Handler:    _ActionService_ListActionExecutions_Handler,
		},
		{
			MethodName: "CreateActionSchema",
			Handler:    _ActionService_CreateActionSchema_Handler,
		},
		{
			MethodName: "ListActionSchemas",
			Handler:    _ActionService_ListActionSchemas_Handler,
		},
		{
			MethodName: "UpdateActionSchema",
			Handler:    _ActionService_UpdateActionSchema_Handler,
		},
		{
			MethodName: "DeleteActionSchema",
			Handler:    _ActionService_DeleteActionSchema_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/v1/action.proto",
}
