// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/proto/v1/action.proto

package apiv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FieldType int32

const (
	FieldType_FIELD_TYPE_UNSPECIFIED FieldType = 0
	FieldType_FIELD_TYPE_STRING      FieldType = 1
	FieldType_FIELD_TYPE_NUMBER      FieldType = 2
	FieldType_FIELD_TYPE_BOOLEAN     FieldType = 3
	FieldType_FIELD_TYPE_ENUM        FieldType = 4
	FieldType_FIELD_TYPE_OBJECT      FieldType = 5
	FieldType_FIELD_TYPE_ARRAY       FieldType = 6
)

// Enum value maps for FieldType.
var (
	FieldType_name = map[int32]string{
		0: "FIELD_TYPE_UNSPECIFIED",
		1: "FIELD_TYPE_STRING",
		2: "FIELD_TYPE_NUMBER",
		3: "FIELD_TYPE_BOOLEAN",
		4: "FIELD_TYPE_ENUM",
		5: "FIELD_TYPE_OBJECT",
		6: "FIELD_TYPE_ARRAY",
	}
	FieldType_value = map[string]int32{
		"FIELD_TYPE_UNSPECIFIED": 0,
		"FIELD_TYPE_STRING":      1,
		"FIELD_TYPE_NUMBER":      2,
		"FIELD_TYPE_BOOLEAN":     3,
		"FIELD_TYPE_ENUM":        4,
		"FIELD_TYPE_OBJECT":      5,
		"FIELD_TYPE_ARRAY":       6,
	}
)

func (x FieldType) Enum() *FieldType {
	p := new(FieldType)
	*p = x
	return p
}

func (x FieldType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FieldType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_v1_action_proto_enumTypes[0].Descriptor()
}

func (FieldType) Type() protoreflect.EnumType {
	return &file_api_proto_v1_action_proto_enumTypes[0]
}

func (x FieldType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FieldType.Descriptor instead.
func (FieldType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_v1_action_proto_rawDescGZIP(), []int{0}
}

type ActionParameter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          FieldType              `protobuf:"varint,2,opt,name=type,proto3,enum=api.v1.FieldType" json:"type,omitempty"`
	Required      bool                   `protobuf:"varint,3,opt,name=required,proto3" json:"required,omitempty"`
	EnumValues    []string               `protobuf:"bytes,4,rep,name=enum_values,json=enumValues,proto3" json:"enum_values,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	DefaultValue  string                 `protobuf:"bytes,6,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionParameter) Reset() {
	*x = ActionParameter{}
	mi := &file_api_proto_v1_action_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionParameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionParameter) ProtoMessage() {}

func (x *ActionParameter) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_action_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionParameter.ProtoReflect.Descriptor instead.
func (*ActionParameter) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_action_proto_rawDescGZIP(), []int{0}
}

func (x *ActionParameter) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ActionParameter) GetType() FieldType {
	if x != nil {
		return x.Type
	}
	return FieldType_FIELD_TYPE_UNSPECIFIED
}

func (x *ActionParameter) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *ActionParameter) GetEnumValues() []string {
	if x != nil {
		return x.EnumValues
	}
	return nil
}

func (x *ActionParameter) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ActionParameter) GetDefaultValue() string {
	if x != nil {
		return x.DefaultValue
	}
	return ""
}

type ActionResultField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          FieldType              `protobuf:"varint,2,opt,name=type,proto3,enum=api.v1.FieldType" json:"type,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Children      []*ActionResultField   `protobuf:"bytes,4,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionResultField) Reset() {
	*x = ActionResultField{}
	mi := &file_api_proto_v1_action_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionResultField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionResultField) ProtoMessage() {}

func (x *ActionResultField) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_action_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionResultField.ProtoReflect.Descriptor instead.
func (*ActionResultField) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_action_proto_rawDescGZIP(), []int{1}
}

func (x *ActionResultField) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ActionResultField) GetType() FieldType {
	if x != nil {
		return x.Type
	}
	return FieldType_FIELD_TYPE_UNSPECIFIED
}

func (x *ActionResultField) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ActionResultField) GetChildren() []*ActionResultField {
	if x != nil {
		return x.Children
	}
	return nil
}

type ActionSchema struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ActionType      string                 `protobuf:"bytes,2,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`
	DisplayName     string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description     string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Parameters      []*ActionParameter     `protobuf:"bytes,5,rep,name=parameters,proto3" json:"parameters,omitempty"`
	ResultSchema    []*ActionResultField   `protobuf:"bytes,6,rep,name=result_schema,json=resultSchema,proto3" json:"result_schema,omitempty"`
	RequireApproval bool                   `protobuf:"varint,7,opt,name=require_approval,json=requireApproval,proto3" json:"require_approval,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ActionSchema) Reset() {
	*x = ActionSchema{}
	mi := &file_api_proto_v1_action_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionSchema) ProtoMessage() {}

func (x *ActionSchema) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_action_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionSchema.ProtoReflect.Descriptor instead.
func (*ActionSchema) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_action_proto_rawDescGZIP(), []int{2}
}

func (x *ActionSchema) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ActionSchema) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

func (x *ActionSchema) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ActionSchema) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ActionSchema) GetParameters() []*ActionParameter {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *ActionSchema) GetResultSchema() []*ActionResultField {
	if x != nil {
		return x.ResultSchema
	}
	return nil
}

func (x *ActionSchema) GetRequireApproval() bool {
	if x != nil {
		return x.RequireApproval
	}
	return false
}

type ActionExecution struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TicketId       string                 `protobuf:"bytes,2,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	ActionType     string                 `protobuf:"bytes,3,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`
	Status         string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // PENDING_APPROVAL, PENDING, IN_PROGRESS, COMPLETED, FAILED, REJECTED
	Parameters     map[string]string      `protobuf:"bytes,5,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ResultMetadata map[string]string      `protobuf:"bytes,6,rep,name=result_metadata,json=resultMetadata,proto3" json:"result_metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ExecutingUser  string                 `protobuf:"bytes,7,opt,name=executing_user,json=executingUser,proto3" json:"executing_user,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ActionExecution) Reset() {
	*x = ActionExecution{}
	mi := &file_api_proto_v1_action_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionExecution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionExecution) ProtoMessage() {}

func (x *ActionExecution) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_action_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionExecution.ProtoReflect.Descriptor instead.
func (*ActionExecution) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_action_proto_rawDescGZIP(), []int{3}
}

func (x *ActionExecution) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ActionExecution) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

func (x *ActionExecution) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

func (x *ActionExecution) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ActionExecution) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *ActionExecution) GetResultMetadata() map[string]string {
	if x != nil {
		return x.ResultMetadata
	}
	return nil
}

func (x *ActionExecution) GetExecutingUser() string {
	if x != nil {
		return x.ExecutingUser
	}
	return ""
}

func (x *ActionExecution) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ActionExecution) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ListActionSchemasRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActionSchemasRequest) Reset() {
	*x = ListActionSchemasRequest{}
	mi := &file_api_proto_v1_action_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActionSchemasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActionSchemasRequest) ProtoMessage() {}

func (x *ListActionSchemasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_action_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActionSchemasRequest.ProtoReflect.Descriptor instead.
func (*ListActionSchemasRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_action_proto_rawDescGZIP(), []int{4}
}

type ListActionSchemasResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schemas       []*ActionSchema        `protobuf:"bytes,1,rep,name=schemas,proto3" json:"schemas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActionSchemasResponse) Reset() {
	*x = ListActionSchemasResponse{}
	mi := &file_api_proto_v1_action_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActionSchemasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActionSchemasResponse) ProtoMessage() {}

func (x *ListActionSchemasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_action_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActionSchemasResponse.ProtoReflect.Descriptor instead.
func (*ListActionSchemasResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_action_proto_rawDescGZIP(), []int{5}
}

func (x *ListActionSchemasResponse) GetSchemas() []*ActionSchema {
	if x != nil {
		return x.Schemas
	}
	return nil
}

type SubmitActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketId      string                 `protobuf:"bytes,1,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	ActionType    string                 `protobuf:"bytes,2,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`
	Parameters    map[string]string      `protobuf:"bytes,3,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitActionRequest) Reset() {
	*x = SubmitActionRequest{}
	mi := &file_api_proto_v1_action_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitActionRequest) ProtoMessage() {}

func (x *SubmitActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_action_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitActionRequest.ProtoReflect.Descriptor instead.
func (*SubmitActionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_action_proto_rawDescGZIP(), []int{6}
}

func (x *SubmitActionRequest) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

func (x *SubmitActionRequest) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

func (x *SubmitActionRequest) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type SubmitActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Execution     *ActionExecution       `protobuf:"bytes,1,opt,name=execution,proto3" json:"execution,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitActionResponse) Reset() {
	*x = SubmitActionResponse{}
	mi := &file_api_proto_v1_action_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitActionResponse) ProtoMessage() {}

func (x *SubmitActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_action_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitActionResponse.ProtoReflect.Descriptor instead.
func (*SubmitActionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_action_proto_rawDescGZIP(), []int{7}
}

func (x *SubmitActionResponse) GetExecution() *ActionExecution {
	if x != nil {
		return x.Execution
	}
	return nil
}

type ListActionExecutionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketId      string                 `protobuf:"bytes,1,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	Pagination    *PaginationRequest     `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActionExecutionsRequest) Reset() {
	*x = ListActionExecutionsRequest{}
	mi := &file_api_proto_v1_action_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActionExecutionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActionExecutionsRequest) ProtoMessage() {}

func (x *ListActionExecutionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_action_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActionExecutionsRequest.ProtoReflect.Descriptor instead.
func (*ListActionExecutionsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_action_proto_rawDescGZIP(), []int{8}
}

func (x *ListActionExecutionsRequest) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

func (x *ListActionExecutionsRequest) GetPagination() *PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListActionExecutionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Executions    []*ActionExecution     `protobuf:"bytes,1,rep,name=executions,proto3" json:"executions,omitempty"`
	Pagination    *PaginationResponse    `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActionExecutionsResponse) Reset() {
	*x = ListActionExecutionsResponse{}
	mi := &file_api_proto_v1_action_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActionExecutionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActionExecutionsResponse) ProtoMessage() {}

func (x *ListActionExecutionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_action_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActionExecutionsResponse.ProtoReflect.Descriptor instead.
func (*ListActionExecutionsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_action_proto_rawDescGZIP(), []int{9}
}

func (x *ListActionExecutionsResponse) GetExecutions() []*ActionExecution {
	if x != nil {
		return x.Executions
	}
	return nil
}

func (x *ListActionExecutionsResponse) GetPagination() *PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

var File_api_proto_v1_action_proto protoreflect.FileDescriptor

const file_api_proto_v1_action_proto_rawDesc = "" +
	"\n" +
	"\x19api/proto/v1/action.proto\x12\x06api.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19api/proto/v1/common.proto\x1a\x1cgoogle/api/annotations.proto\"\xd0\x01\n" +
	"\x0fActionParameter\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\x04type\x18\x02 \x01(\x0e2\x11.api.v1.FieldTypeR\x04type\x12\x1a\n" +
	"\brequired\x18\x03 \x01(\bR\brequired\x12\x1f\n" +
	"\venum_values\x18\x04 \x03(\tR\n" +
	"enumValues\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12#\n" +
	"\rdefault_value\x18\x06 \x01(\tR\fdefaultValue\"\xa7\x01\n" +
	"\x11ActionResultField\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\x04type\x18\x02 \x01(\x0e2\x11.api.v1.FieldTypeR\x04type\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x125\n" +
	"\bchildren\x18\x04 \x03(\v2\x19.api.v1.ActionResultFieldR\bchildren\"\xa8\x02\n" +
	"\fActionSchema\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vaction_type\x18\x02 \x01(\tR\n" +
	"actionType\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x127\n" +
	"\n" +
	"parameters\x18\x05 \x03(\v2\x17.api.v1.ActionParameterR\n" +
	"parameters\x12>\n" +
	"\rresult_schema\x18\x06 \x03(\v2\x19.api.v1.ActionResultFieldR\fresultSchema\x12)\n" +
	"\x10require_approval\x18\a \x01(\bR\x0frequireApproval\"\xb5\x04\n" +
	"\x0fActionExecution\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tticket_id\x18\x02 \x01(\tR\bticketId\x12\x1f\n" +
	"\vaction_type\x18\x03 \x01(\tR\n" +
	"actionType\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12G\n" +
	"\n" +
	"parameters\x18\x05 \x03(\v2'.api.v1.ActionExecution.ParametersEntryR\n" +
	"parameters\x12T\n" +
	"\x0fresult_metadata\x18\x06 \x03(\v2+.api.v1.ActionExecution.ResultMetadataEntryR\x0eresultMetadata\x12%\n" +
	"\x0eexecuting_user\x18\a \x01(\tR\rexecutingUser\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aA\n" +
	"\x13ResultMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x1a\n" +
	"\x18ListActionSchemasRequest\"K\n" +
	"\x19ListActionSchemasResponse\x12.\n" +
	"\aschemas\x18\x01 \x03(\v2\x14.api.v1.ActionSchemaR\aschemas\"\xdf\x01\n" +
	"\x13SubmitActionRequest\x12\x1b\n" +
	"\tticket_id\x18\x01 \x01(\tR\bticketId\x12\x1f\n" +
	"\vaction_type\x18\x02 \x01(\tR\n" +
	"actionType\x12K\n" +
	"\n" +
	"parameters\x18\x03 \x03(\v2+.api.v1.SubmitActionRequest.ParametersEntryR\n" +
	"parameters\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"M\n" +
	"\x14SubmitActionResponse\x125\n" +
	"\texecution\x18\x01 \x01(\v2\x17.api.v1.ActionExecutionR\texecution\"u\n" +
	"\x1bListActionExecutionsRequest\x12\x1b\n" +
	"\tticket_id\x18\x01 \x01(\tR\bticketId\x129\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x19.api.v1.PaginationRequestR\n" +
	"pagination\"\x93\x01\n" +
	"\x1cListActionExecutionsResponse\x127\n" +
	"\n" +
	"executions\x18\x01 \x03(\v2\x17.api.v1.ActionExecutionR\n" +
	"executions\x12:\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1a.api.v1.PaginationResponseR\n" +
	"pagination*\xaf\x01\n" +
	"\tFieldType\x12\x1a\n" +
	"\x16FIELD_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11FIELD_TYPE_STRING\x10\x01\x12\x15\n" +
	"\x11FIELD_TYPE_NUMBER\x10\x02\x12\x16\n" +
	"\x12FIELD_TYPE_BOOLEAN\x10\x03\x12\x13\n" +
	"\x0fFIELD_TYPE_ENUM\x10\x04\x12\x15\n" +
	"\x11FIELD_TYPE_OBJECT\x10\x05\x12\x14\n" +
	"\x10FIELD_TYPE_ARRAY\x10\x062\xff\x02\n" +
	"\rActionService\x12t\n" +
	"\x11ListActionSchemas\x12 .api.v1.ListActionSchemasRequest\x1a!.api.v1.ListActionSchemasResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/action-schemas\x12a\n" +
	"\fSubmitAction\x12\x1b.api.v1.SubmitActionRequest\x1a\x1c.api.v1.SubmitActionResponse\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/v1/actions\x12\x94\x01\n" +
	"\x14ListActionExecutions\x12#.api.v1.ListActionExecutionsRequest\x1a$.api.v1.ListActionExecutionsResponse\"1\x82\xd3\xe4\x93\x02+\x12)/v1/tickets/{ticket_id}/action-executionsB7Z5github.com/squall-chua/go-support-ticket/api/v1;apiv1b\x06proto3"

var (
	file_api_proto_v1_action_proto_rawDescOnce sync.Once
	file_api_proto_v1_action_proto_rawDescData []byte
)

func file_api_proto_v1_action_proto_rawDescGZIP() []byte {
	file_api_proto_v1_action_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_action_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_action_proto_rawDesc), len(file_api_proto_v1_action_proto_rawDesc)))
	})
	return file_api_proto_v1_action_proto_rawDescData
}

var file_api_proto_v1_action_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_v1_action_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_proto_v1_action_proto_goTypes = []any{
	(FieldType)(0),                       // 0: api.v1.FieldType
	(*ActionParameter)(nil),              // 1: api.v1.ActionParameter
	(*ActionResultField)(nil),            // 2: api.v1.ActionResultField
	(*ActionSchema)(nil),                 // 3: api.v1.ActionSchema
	(*ActionExecution)(nil),              // 4: api.v1.ActionExecution
	(*ListActionSchemasRequest)(nil),     // 5: api.v1.ListActionSchemasRequest
	(*ListActionSchemasResponse)(nil),    // 6: api.v1.ListActionSchemasResponse
	(*SubmitActionRequest)(nil),          // 7: api.v1.SubmitActionRequest
	(*SubmitActionResponse)(nil),         // 8: api.v1.SubmitActionResponse
	(*ListActionExecutionsRequest)(nil),  // 9: api.v1.ListActionExecutionsRequest
	(*ListActionExecutionsResponse)(nil), // 10: api.v1.ListActionExecutionsResponse
	nil,                                  // 11: api.v1.ActionExecution.ParametersEntry
	nil,                                  // 12: api.v1.ActionExecution.ResultMetadataEntry
	nil,                                  // 13: api.v1.SubmitActionRequest.ParametersEntry
	(*timestamppb.Timestamp)(nil),        // 14: google.protobuf.Timestamp
	(*PaginationRequest)(nil),            // 15: api.v1.PaginationRequest
	(*PaginationResponse)(nil),           // 16: api.v1.PaginationResponse
}
var file_api_proto_v1_action_proto_depIdxs = []int32{
	0,  // 0: api.v1.ActionParameter.type:type_name -> api.v1.FieldType
	0,  // 1: api.v1.ActionResultField.type:type_name -> api.v1.FieldType
	2,  // 2: api.v1.ActionResultField.children:type_name -> api.v1.ActionResultField
	1,  // 3: api.v1.ActionSchema.parameters:type_name -> api.v1.ActionParameter
	2,  // 4: api.v1.ActionSchema.result_schema:type_name -> api.v1.ActionResultField
	11, // 5: api.v1.ActionExecution.parameters:type_name -> api.v1.ActionExecution.ParametersEntry
	12, // 6: api.v1.ActionExecution.result_metadata:type_name -> api.v1.ActionExecution.ResultMetadataEntry
	14, // 7: api.v1.ActionExecution.created_at:type_name -> google.protobuf.Timestamp
	14, // 8: api.v1.ActionExecution.updated_at:type_name -> google.protobuf.Timestamp
	3,  // 9: api.v1.ListActionSchemasResponse.schemas:type_name -> api.v1.ActionSchema
	13, // 10: api.v1.SubmitActionRequest.parameters:type_name -> api.v1.SubmitActionRequest.ParametersEntry
	4,  // 11: api.v1.SubmitActionResponse.execution:type_name -> api.v1.ActionExecution
	15, // 12: api.v1.ListActionExecutionsRequest.pagination:type_name -> api.v1.PaginationRequest
	4,  // 13: api.v1.ListActionExecutionsResponse.executions:type_name -> api.v1.ActionExecution
	16, // 14: api.v1.ListActionExecutionsResponse.pagination:type_name -> api.v1.PaginationResponse
	5,  // 15: api.v1.ActionService.ListActionSchemas:input_type -> api.v1.ListActionSchemasRequest
	7,  // 16: api.v1.ActionService.SubmitAction:input_type -> api.v1.SubmitActionRequest
	9,  // 17: api.v1.ActionService.ListActionExecutions:input_type -> api.v1.ListActionExecutionsRequest
	6,  // 18: api.v1.ActionService.ListActionSchemas:output_type -> api.v1.ListActionSchemasResponse
	8,  // 19: api.v1.ActionService.SubmitAction:output_type -> api.v1.SubmitActionResponse
	10, // 20: api.v1.ActionService.ListActionExecutions:output_type -> api.v1.ListActionExecutionsResponse
	18, // [18:21] is the sub-list for method output_type
	15, // [15:18] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_api_proto_v1_action_proto_init() }
func file_api_proto_v1_action_proto_init() {
	if File_api_proto_v1_action_proto != nil {
		return
	}
	file_api_proto_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_action_proto_rawDesc), len(file_api_proto_v1_action_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_action_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_action_proto_depIdxs,
		EnumInfos:         file_api_proto_v1_action_proto_enumTypes,
		MessageInfos:      file_api_proto_v1_action_proto_msgTypes,
	}.Build()
	File_api_proto_v1_action_proto = out.File
	file_api_proto_v1_action_proto_goTypes = nil
	file_api_proto_v1_action_proto_depIdxs = nil
}
