// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/proto/v1/options.proto

package apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthRule struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequiredScopes []string               `protobuf:"bytes,1,rep,name=required_scopes,json=requiredScopes,proto3" json:"required_scopes,omitempty"`
	RequiredRoles  []string               `protobuf:"bytes,2,rep,name=required_roles,json=requiredRoles,proto3" json:"required_roles,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AuthRule) Reset() {
	*x = AuthRule{}
	mi := &file_api_proto_v1_options_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRule) ProtoMessage() {}

func (x *AuthRule) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_options_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRule.ProtoReflect.Descriptor instead.
func (*AuthRule) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_options_proto_rawDescGZIP(), []int{0}
}

func (x *AuthRule) GetRequiredScopes() []string {
	if x != nil {
		return x.RequiredScopes
	}
	return nil
}

func (x *AuthRule) GetRequiredRoles() []string {
	if x != nil {
		return x.RequiredRoles
	}
	return nil
}

var file_api_proto_v1_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*AuthRule)(nil),
		Field:         50000,
		Name:          "auth.v1.rule",
		Tag:           "bytes,50000,opt,name=rule",
		Filename:      "api/proto/v1/options.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional auth.v1.AuthRule rule = 50000;
	E_Rule = &file_api_proto_v1_options_proto_extTypes[0]
)

var File_api_proto_v1_options_proto protoreflect.FileDescriptor

const file_api_proto_v1_options_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/proto/v1/options.proto\x12\aauth.v1\x1a google/protobuf/descriptor.proto\"Z\n" +
	"\bAuthRule\x12'\n" +
	"\x0frequired_scopes\x18\x01 \x03(\tR\x0erequiredScopes\x12%\n" +
	"\x0erequired_roles\x18\x02 \x03(\tR\rrequiredRoles:G\n" +
	"\x04rule\x12\x1e.google.protobuf.MethodOptions\x18І\x03 \x01(\v2\x11.auth.v1.AuthRuleR\x04ruleB7Z5github.com/squall-chua/go-support-ticket/api/v1;apiv1b\x06proto3"

var (
	file_api_proto_v1_options_proto_rawDescOnce sync.Once
	file_api_proto_v1_options_proto_rawDescData []byte
)

func file_api_proto_v1_options_proto_rawDescGZIP() []byte {
	file_api_proto_v1_options_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_options_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_options_proto_rawDesc), len(file_api_proto_v1_options_proto_rawDesc)))
	})
	return file_api_proto_v1_options_proto_rawDescData
}

var file_api_proto_v1_options_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_proto_v1_options_proto_goTypes = []any{
	(*AuthRule)(nil),                   // 0: auth.v1.AuthRule
	(*descriptorpb.MethodOptions)(nil), // 1: google.protobuf.MethodOptions
}
var file_api_proto_v1_options_proto_depIdxs = []int32{
	1, // 0: auth.v1.rule:extendee -> google.protobuf.MethodOptions
	0, // 1: auth.v1.rule:type_name -> auth.v1.AuthRule
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_v1_options_proto_init() }
func file_api_proto_v1_options_proto_init() {
	if File_api_proto_v1_options_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_options_proto_rawDesc), len(file_api_proto_v1_options_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_v1_options_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_options_proto_depIdxs,
		MessageInfos:      file_api_proto_v1_options_proto_msgTypes,
		ExtensionInfos:    file_api_proto_v1_options_proto_extTypes,
	}.Build()
	File_api_proto_v1_options_proto = out.File
	file_api_proto_v1_options_proto_goTypes = nil
	file_api_proto_v1_options_proto_depIdxs = nil
}
