approval_config:
  queue_type: kafka
  dlq_postfix: .failed
  destinations:
    - approval-config-events
  events:
    approval_config.created:
    approval_config.updated:
    approval_config.deleted:

approval:
  queue_type: kafka
  dlq_postfix: .failed
  destinations:
    - approval-events
  events:
    approval.requested:
    approval.pending:
    approval.decided:

action:
  queue_type: kafka
  dlq_postfix: .failed
  destinations:
    - action-events
  events:
    action.schema.created:
    action.schema.updated:
    action.schema.deleted:
    action.execution.status.updated:
    action.execution.triggered:
    action.execution.completed:
    action.execution.pending_approval:

ticket_type:
  queue_type: kafka
  dlq_postfix: .failed
  destinations:
    - ticket-type-events
  events:
    ticket_type.created:
    ticket_type.updated:
    ticket_type.deleted:

ticket:
  queue_type: kafka
  dlq_postfix: .failed
  destinations:
    - ticket-events
  events:
    ticket.created:
    ticket.updated:
    ticket.assigned:
    ticket.comment.added:
    ticket.update.pending_approval:
    ticket.merged:
    ticket.merge.pending_approval:
    ticket.deleted:
